#!/bin/bash

. test-hstm-library

if [ 1 == 1 ]; then

echo basic sketch
iquery --port 1439 -aq \
    "build(<val: string>[i=0:0,1,0], symbol(hstmFromLevelLatLon(8,45.0,45.0)))"

echo test 1
iquery --port 1439 -aq \
    "build(<val: bool>[i=0:0,1,0], 'xxx' = symbol(hstmFromLevelLatLon(8,45.0,45.0)))"

echo test 2 failing string test
assert_equal xxx 'symbol(hstmFromLevelLatLon(8,45.0,45.0))'

echo test 3.1 failing string test, with annoying extra space?
assert_equal '(HSTMSymbolic N333133333 N333133333) ' 'symbol(hstmFromLevelLatLon(8,45.0,45.0))'

echo test 3.2 passing string test, no annoying extra space?
assert_equal '(HSTMSymbolic N333133333 N333133333)' 'symbol(hstmFromLevelLatLon(8,45.0,45.0))'

echo test 4.1 integers
assert_equal_int64 99 'hstmFromLevelLatLon(8,45.0,45.0)'

echo test 4.2 symbol
assert_equal xxx "symbol(hstm('(HSTMSymbolic N3333333333333333333333333333)'))"

# echo example 4.2.1
# iquery --port 1439 -aq "build(<val: string>[i=0:0,1,0], symbol(hstm('(HSTMSymbolic N3333333333333333333333333333)')))"
# iquery --port 1439 -aq "build(<val: string>[i=0:0,1,0], symbol(hstm('(HSTMSymbolic N3333)')))"
# iquery --port 1439 -aq "build(<val: string>[i=0:0,1,0], symbol(hstm('(HSTMSymbolic N3333 N3333)')))"
# iquery --port 1439 -aq "build(<val: string>[i=0:0,1,0], hstmFromLevelLatLon(8,45.0,45.0))"
# iquery --port 1439 -aq "build(<val: string>[i=0:0,1,0], hstm('(HSTMHex x7f7ff00000000008 x7f7fffffffffffff)'))"
# iquery --port 1439 -aq "build(<val: string>[i=0:0,1,0], index(hstm('(HSTMHex x7f7ff00000000008 x7f7fffffffffffff)')))"

# iquery --port 1439 -aq "build(<val: string>[i=0:0,1,0], level(hstm('(HSTMHex x7f7ff00000000008 x7f7fffffffffffff)')))"
# iquery --port 1439 -aq "build(<val: int64>[i=0:0,1,0],positionFromHstm(hstmFromLevelLatLon(8,45.0,45.0),0,'lat'));"

fi

echo test 5. Check lat lon
assert_equal "(HSTMHex x7f7ff00000000008 x7f7fffffffffffff)" "string(hstmFromLevelLatLon(8,45.0,45.0))"
#assert_equal "4593662823824883720" "string(hstmFromLevelLatLon(8,45.0,45.0))"

echo test 5.1 lat-lon and nodeIndex
assert_equal "45.1468735700533" "string(positionFromHstm(hstmFromLevelLatLon(8,45.0,45.0),0,'lat'))"

echo test 5.2 FAILING lat-lon and nodeIndex bad parameter lati
iquery --port 1439 -aq "build(<val:string>[i1=0:0,1,0],string(positionFromHstm(hstmFromLevelLatLon(8,45.0,45.0),0,'lati')))"

echo test 5.3 FAILING lat-lon and nodeIndex out of bounds vector number
iquery --port 1439 -aq "build(<val:string>[i1=0:0,1,0],string(positionFromHstm(hstmFromLevelLatLon(8,45.0,45.0),20,'lat')))"

echo $0 done
