#!/bin/bash

# (shell-command-to-string buffer-file-name)
# (shell-command-to-string (concat "chmod ugo+rx "buffer-file-name))
# (shell-command-to-string "iquery -aq \"list('functions');\" | grep -i temporal;")

. test-hstm-library

echo -n "1 "
assert_equal '0000-00-01 00:00:14.664 (03)'       "stringFromTemporalIndex(120003)"

echo -n "2 "
assert_equal '000-000000-00-0-0 00:0014.664 (03)' "nativeStringFromTemporalIndex(120003)"

echo -n "3 "
# TODO verify the index below
assert_equal_int64 9830403 "temporalIndexFromTradYrMoDyHrMiSeMsRl(0,0,1,0,20,0,0,3)"

echo -n "4 "
# Note that the day field in the string starts at zero. <sigh/>
assert_equal "000-000000-00-0-0 00:1200.000 (03)" "nativeStringFromTemporalIndex(temporalIndexFromTradYrMoDyHrMiSeMsRl(0,0,1,0,20,0,0,3))"
echo -n "5 "
assert_equal "0000-00-01 00:20:00.000 (03)" "stringFromTemporalIndex(temporalIndexFromTradYrMoDyHrMiSeMsRl(0,0,1,0,20,0,0,3))"

echo -n "6 "
assert_equal_int64 120003 "temporalIndexFromNativeString(nativeStringFromTemporalIndex(120003))"

echo -n "7 "
assert_equal_int64 120003 "temporalIndexFromString(stringFromTemporalIndex(120003))"

echo -n "8 "
assert_equal_int64 4 "firstBitDifferenceFromLeft(
temporalIndexFromTradYrMoDyHrMiSeMsRl( 14999999,0,1,0,20,0,0,0),
temporalIndexFromTradYrMoDyHrMiSeMsRl( 15000000,0,1,0,20,1,0,0)
)"
# Which bit is different?
# Diff at ms = 60
# Diff in level = 61-63
# Equal = 64

echo -n "9 "
assert_equal_int64 0 "temporalIndexFromTradYrMoDyHrMiSeMsRl( 0,0,1,0,0,0,0,0)"

echo -n "10 "
assert_equal_int64 8 "temporalIndexFromTradYrMoDyHrMiSeMsRl( 0,0,1,0,0,0,1,0)"

# assert_equal_int64 -1 "temporalIndexFromTradYrMoDyHrMiSeMsRl( 1,0,1,0,20,1,0,0)"
# assert_equal_int64 -1 "temporalIndexFromTradYrMoDyHrMiSeMsRl( 2,0,1,0,20,1,0,0)"
# assert_equal_int64 -1 "temporalIndexFromTradYrMoDyHrMiSeMsRl( 3,0,1,0,20,1,0,0)"
# assert_equal_int64 -1 "temporalIndexFromTradYrMoDyHrMiSeMsRl(   149999,0,1,0,20,1,0,0)"
# assert_equal_int64 -1 "temporalIndexFromTradYrMoDyHrMiSeMsRl(  1499999,0,1,0,20,1,0,0)"
# 9209847941555158840
# assert_equal_int64 -1 "temporalIndexFromTradYrMoDyHrMiSeMsRl( 15999999,11,31,23,59,59,999,0)"
echo -n "11 "
assert_equal_int64 9209847941555158840 "temporalIndexFromTradYrMoDyHrMiSeMsRl( 15999999,11,31,23,59,59,999,0)"
# assert_equal_int64 -1 "temporalIndexFromTradYrMoDyHrMiSeMsRl( 16000000,11,31,23,59,59,999,0)"

echo -n "12 "
assert_equal_int64 1131256804802560 "temporalIndexFromTradYrMoDyHrMiSeMsRl( 2009,11,1,0,0,0,0,0)"
assert_equal_int64 1131256838356992 "temporalIndexFromTradYrMoDyHrMiSeMsRl( 2009,11,1,1,0,0,0,0)"
# 1131256804802560
# 1131256838356992


echo -n "13 "
assert_equal_int64 3362563568582000651 "indexFromHstm(hstmFromIndex(3362563568582000651))"

# # 3362563568582000651
# assert_equal_int64 -1 "indexFromHstm(hstmFromLevelLatLon(11,20-0.005,-130-0.005))"
# # 2502629202306531339
# assert_equal_int64 -1 "indexFromHstm(hstmFromLevelLatLon(11,55+0.005, -60+0.005))"
# 
# # 3362563568582000651
# assert_equal_int64 -1 "indexFromHstm(hstmFromLevelLatLon(11,20,-130))"
# # 2500271849376579595
# assert_equal_int64 -1 "indexFromHstm(hstmFromLevelLatLon(11,55, -60))"
# 
# #fail assert_equal_int64 -1 "0xff and 0x0f"
# #fail assert_equal_int64 -1 "255 & 15"
# #fail assert_equal_int64 -1 "255 && 15"

# assert_equal_int64 -1 "indexFromHstm(idToLevel(hstmFromIndex(3362563568582000651),7))"
# assert_equal_int64 -1 "indexFromHstm(idToLevel(hstmFromIndex(3362535531035492359),11))"

#broken assert_equal_int64 -1 "level(hstmFromIndex(3362563568582000651))"



echo
